### ISSUE TITLE
Bootstrap boilerplate on Windows

### ISSUE THREAD

**Issue by AnnotatedJS** [meteor-useraccounts/boilerplates#10]
I installed the Bootstrap boilerplate on Windows and that needs an extra step.

This step is mentioned in the following error message,

This project uses METEOR@1.0.4.1, which isn't available on Windows. To work with this app on all supported platforms, use meteor update --release WINDOWS-PREVIEW@0.3.0 to pin this app to the
newest Windows-compatible release.

**Comment by splendido** [comment]
I'm sorry for that.

Where you eventually able to run the apps?
In case, we could add a section on the README to instruct how to run everything also on Windows!
