### ISSUE TITLE
router.js should be moved to client

### ISSUE THREAD

**Issue by dandv** [meteor-useraccounts/boilerplates#15]
https://github.com/meteor-useraccounts/boilerplates/blob/master/materialize-flow-router/lib/router.js is in `lib` because of cloning after the iron-router example, but FlowRouter is client only.

**Comment by splendido** [comment]
yeah!
we should also update all IR examples and move all configuration stuff to have general router configuration being loaded before UserAccounts configuration and useraccounts routes defined after useraccounts options.
